config/routes.rb
Rails.application.routes.draw do
  match '/signup', to: 'users#new', via: :get  
  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users
  resources :messages,    only: [:show, :create, :destroy] do
    resources :comments, only: [:show, :create]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :friends, only: [:create]
  match '/unfriend/:friend_id', to: "friends#breakup", as: :breakup, via: :delete
  match '/block/:id', to: "users#block", as: :block, via: :post
  match '/unblock', to: "users#unblock", as: :unblock, via: :post
  match '/release_all', to: "users#unblock_all_users", as: :release_all, via: :post

  root 'home#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user

  validates :user_id, :message_id, :content, presence: true

  def self.default_scope
    order("created_at DESC")
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user, class_name: "User"
  belongs_to :friend, class_name: "User"

  validates_presence_of :user_id, :friend_id
  
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :content, :user_id, presence: true

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, length: {maximum: 25}
  validates :email, presence: true
  validates :password, length: { minimum: 8}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  before_save { email.downcase! }
  before_create :create_remember_token

  has_many :messages
  has_many :friendships
  has_many :friends, through: :friendships

  def User.default_scope
    where(blocked: false)
  end

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def friends_with?(user)
    friends.include?(user)
  end

  def befriend(friend)
    transaction do
      self.friendships.create(friend_id: friend.id)
      friend.friendships.create(friend_id: self.id)
    end
  end

  def breakup_with(friend)
    transaction do
      self.friendships.where(friend_id: friend.id).first.destroy
      friend.friendships.where(friend_id: self.id).first.destroy
    end
  end

  def ban(user)
    self.blocked = true
    self.blocked_by = user.id
    self.save(validate: false)
  end

  def blocked?
    blocked
  end

  def unban
    self.blocked = false
    self.blocked_by = nil
    self.save(validate: false)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :signed_in_user

  def create
    @message = Message.find(params[:message_id])
    @comment = @message.comments.create(
      content: params[:comment][:content],
      user_id: current_user.id
    )
    
    if @comment.save
      flash[:success] = "comment created!"
    else
      flash[:error] = "comment not created!"
    end
    redirect_to @message
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  
  def create
    @user = User.find(params[:friend_id])
    current_user.befriend(@user)
    
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  def breakup
    @user = User.find(params[:friend_id])
    current_user.breakup_with(@user)
    
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @users = User.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :find_user,   only: :destroy

  def show
    @message = Message.find(params[:id])
  end

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      flash[:success] = "message created!"
      redirect_to current_user
    else
      flash[:error] = "message not created!"
      redirect_to current_user
    end
  end

  def destroy
    @message.destroy
    redirect_to current_user
  end

  private

    def message_params
      params.require(:message).permit(:content)
    end

    def find_user
      @message = current_user.messages.find_by(id: params[:id])
      redirect_to root_url if @message.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_url
    else
      flash.now[:error] = 'Invalid email/password'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, except: [:new, :create, :show]
  before_action :find_user, except: [:new, :create, :show, :unblock_all_users]

  def show
    @user = User.find(params[:id])
    @messages = @user.messages
    @friends = @user.friends
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome #{@user.name}"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Update successful for #{@user.name}"
      redirect_to current_user
    else
      render 'edit'
    end
  end

  def block
    @user.ban(current_user)

    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  def unblock
    @user.unban

    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  def unblock_all_users
    User.unscoped.update_all(blocked: false)

    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
      :password_confirmation)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token  = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/views/comments/_comment.html.erb
<li>
  <div class="comment">
    <span>user: <%= comment.user.name %></span><br/>
    <span>comment: <%= comment.content %></span>
  </div>
  <br/>
</li>

app/views/comments/_comment_form.html.erb
<div class="comment-form-container">
   <%= form_for([@message, Comment.new]) do |f| %>
    <div class="form-line">
      <div class="textarea-container">
        <%= f.text_area :content %>
      </div>
    </div>
      <button class="bttn">Comment</button>
  <% end %>
</div>

app/views/comments/create.js.erb
alert("Comment added");

location.reload();

app/views/friends/breakup.js.erb
location.reload();

app/views/friends/create.js.erb
location.reload();

app/views/home/index.html.erb
<div class="center hero-unit">
  <h1>Welcome to Pulse </h1>
  <h2>
    A quick demo
  </h2>  
  <div>
    <h3>List of Other Pulsers</h3>
    <ul>
      <% @users.each do |user| %>
        <% next if current_user && current_user == user %>
        <%= render "users/user", user: user %>
      <% end %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Darwin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    
    <% if current_user %>
      <%= render "shared/nav"%>
    <% else %>
      <%= link_to "Sign in", signin_path %> | Don't have an account? <%= link_to "Sign up", signup_path, class: "btn btn-large btn-primary" %>
    <% end %>
    
    <%= yield %>
  </div>

</body>
</html>

app/views/messages/_message.html.erb
<li>
  <span class="content"><%= link_to "#{message.content}", message %></span> | <span>Posted by: <%= message.user.name%></span>
  <span class="timestamp">
    | Posted <%= time_ago_in_words(message.created_at) %> ago.
  </span>
  <% if current_user?(message.user) %>
    <%= link_to "delete", message, method: :delete,
                                     data: { confirm: "Are you sure?" },
                                     title: message.content %>
  <% end %>
</li>

app/views/messages/_message_form.html.erb
<%= form_for(Message.new) do |f| %>
  <div id="post" class="field">
    <%= f.text_area :content, placeholder: "Post new message..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/messages/show.html.erb
<h1><%= link_to "Showing Message", root_path %></h1>

<div class="row">
  <div class="span6 offset3"> 
    <%= @message.content %>
  </div>
  <%= render "comments/comment_form" %>
</div>
<div class="row">
  <h1>Comments</h1>
    <ul>
      <%= render partial: "comments/comment", collection: @message.comments %>
    </ul>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<div id="menu">
  <% if signed_in? %>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "View Profile", current_user %></li>
      <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
      <li><%= link_to "Unblock All User", release_all_path, remote: true, method: :post %></li>
      <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
    </ul>
  <% end %>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to "#{user.name}", user %> | <%= user.email %>
  <% if signed_in? %>
    <% if current_user.friends_with?(user) %>
      <%= link_to "Breakup with #{user.name}", breakup_path(friend_id: user.id), remote: true, method: :delete %>
    <% else %>
      <%= link_to "Befriend #{user.name}", friends_path(friend_id: user.id), remote: true, method: :post %>
    <% end %>
    | 
    <% if user.blocked? %>
      <%= link_to "Unblock User", unblock_path(id: user.id), remote: true, method: :post %>
    <% else %>
      <%= link_to "Block #{user.name}", block_path(id: user.id), remote: true, method: :post %>
    <% end %>
  <% end %>
</li><br />

app/views/users/block.js.erb
alert("User Blocked");

location.reload();

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <% if signed_in? && current_user != @user %>
          <%= "#{current_user.name} is viewing #{@user.name}'s page"%>
        <% else %>
          <%= "#{@user.name} | #{@user.email}" %>
        <% end %>
      </h1>
    </section>
  </aside>
</div>

<div id="posts">
  <h1>Posts</h1>
  <p>Post count: <%= @messages.count %></p>
  <ul>
    <%= render partial: "messages/message", collection: @messages %>
  </ul>
  <div id="new-post">New Post
    <%= render partial: "messages/message_form" %>
  </div>
</div>

<div id="friends">
  <h1>Friend list</h1>
    <% if @friends.any? %></p>
      <ul>
        <%= render partial: "users/user", collection: @friends %>
      </ul>
    <% else %>
      <p>No friends found.</p>
    <% end %>
</div>

<div id="friends-messages">
  <h1>Friend's messages</h1>
    <% if @friends.any? %></p>
      <ul> 
        <% @friends.each do |friend| %>
          <%= render partial: "messages/message", collection: friend.messages %>
        <% end %>
      </ul>
    <% else %>
      <p>No friend's messages found.</p>
    <% end %>
</div>

app/views/users/unblock.js.erb
location.reload();

app/views/users/unblock_all_users.js.erb
alert("All Users unblocked!");

location.reload();